---
- name: "create bond slave configuration"
  template:
    src: "bond/bond_slave_{{ ansible_os_family | lower() }}.j2"
    dest: "{{ interfaces_config_path }}/ifcfg-{{ item.1 }}"
  with_subelements:
    - "{{ network_bond_interfaces }}"
    - bond_slaves

- name: "create bond devices configuration"
  template:
    src: "bond/bond_{{ ansible_os_family | lower() }}.j2"
    dest: "{{ interfaces_config_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_bond_interfaces }}"
  register: bond_configuration

- name: "load kernel bonding module"
  modprobe:
    name: bonding
    state: present
  when: bond_configuration is changed

- name: "add kernel bonding module to loaded modules"
  lineinfile:
    line: 'bonding'
    dest: /etc/modules
    insertafter: EOF
  when: network_modprobe_persist
