---
- name: "create bridge configuration"
  template:
    src: "bridge/bridge_{{ ansible_os_family | lower() }}.j2"
    dest: "{{ interfaces_config_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_bridge_interfaces }}"

- name: "create bridge ports configuration"
  template:
    src: "bridge/bridge_port_{{ ansible_os_family | lower() }}.j2"
    dest: "{{ interfaces_config_path }}/ifcfg-{{ item.1 }}"
  with_subelements:
    - "{{ network_bridge_interfaces }}"
    - bridge_ports
