---
- name: "install debian required packages"
  apt:
    name: "{{ network_pkgs }}"
    state: present
    update_cache: yes
  environment: "{{ env }}"
  when: network_check_packages

- name: "enable interfaces.d sourcing"
  lineinfile:
    regexp: '^source\ {{ interfaces_config_path | regex_escape() }}/\*'
    line: "source {{ interfaces_config_path }}/*"
    dest: "/etc/network/interfaces"
    state: present
    insertafter: EOF

- name: "ensure that etc/interfaces.d exists"
  file:
    path: "{{ interfaces_config_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
