---
- name: "create ethernet interface configuration"
  template:
    src: "ethernet/ethernet_{{ ansible_os_family | lower() }}.j2"
    dest: "{{ interfaces_config_path }}/ifcfg-{{ item.device }}"
  loop: "{{ network_ether_interfaces }}"
  notify: "restart networking"
