---
- name: "include {{ ansible_os_family }} variables"
  include_vars: "{{ ansible_os_family | lower() }}.yml"

- name: "include {{ ansible_os_family }} tasks"
  include_tasks: "{{ ansible_os_family | lower() }}.yml"

- name: "include ethernet configuration"
  include_tasks: "ethernet.yml"
  when:
    - network_ether_interfaces and network_ether_interfaces is defined
    - network_ether_interfaces | length() > 0

- name: "include bridge configuration"
  include_tasks: "bridge.yml"
  when:
    - network_bridge_interfaces and network_bridge_interfaces is defined
    - network_bridge_interfaces | length() > 0

- name: "include bonding configuration"
  include_tasks: "bonding.yml"
  when:
    - network_bond_interfaces and network_bond_interfaces is defined
    - network_bond_interfaces | length() > 0

- name: "include vlan configuration"
  include_tasks: "vlan.yml"
  when:
    - network_vlan_interfaces and network_vlan_interfaces is defined
    - network_vlan_interfaces | length() > 0


# Restart Network Interfaces (deconfigurate & reconfigurate interfaces)
- include: restartscript.yml
  when: network_allow_service_restart and ansible_os_family == 'Debian'
