---
- name: "create vlan configuration"
  template:
    src: "ethernet/ethernet_{{ ansible_os_family | lower() }}.j2"
    dest: "{{ interfaces_config_path }}/ifcfg-{{ item.device }}"
  with_items: "{{ network_vlan_interfaces }}"
  register: vlan_configuration

- name: "load kernel module 8021q"
  modprobe:
    name: "8021q"
    state: present
  when: vlan_configuration is changed

- name: "add kernel 8021q module to loaded modules"
  lineinfile:
    line: "8021q"
    dest: "/etc/modules"
    insertafter: EOF
  when: network_modprobe_persist
